- .github/CODEOWNERS
> Add noot to codeowners

- .github/CODEOWNERS
- Add @mmacedoeu to code owners
Closes 
> Add marcos to codeonwers

- base/src/numbers.rs
- base/src/protocol_state.rs
- test-serialization/src/lib.rs
- wire-type-derive/src/lib.rs
- Impl strongly-typed ProtocolConstants 
- Tests
Part of #55 
Closes 
> Impl ProtocolConstants

- base/src/blockchain_state.rs
- base/src/consensus_state.rs
- base/src/epoch_data.rs
- base/src/global_slot.rs
- base/src/lib.rs
- base/src/numbers.rs
- base/src/protocol_state.rs
- base/src/token_id.rs
- consensus/src/common.rs
- crypto/src/hash/types.rs
- test-serialization/src/lib.rs
- Implement strongly-typed ProtocolStateBody
- Unit tests refactoring
- Expose all base types under types namespace
Part of #55  
Closes  #2 
> Implement strongly-typed ProtocolStateBody

- README.md
- Add badges for CI and codecov to readme.md
Closes 
> Badges for CI and codecov

- .github/workflows/build-and-test.yml
- README.md
- base/src/external_transition.rs
- base/src/numbers.rs
- codecov.yml
- crypto/src/base58/version_bytes.rs
- crypto/src/hash/types.rs
- Add/Fix some docs / doc tests
- Run doc gen in CI job
- codecov ignore test tools and test projects
- Cache cargo-deny to speed up checks job
- loc(lines of code) badge
Closes 
> Run doc gen/test in CI

- .github/workflows/build-and-test.yml
- Cargo.lock
- base/src/consensus_state.rs
- base/src/protocol_state.rs
- base/src/staged_ledger_diff.rs
- base/src/token_id.rs
- crypto/src/hash/types.rs
- crypto/src/signature.rs
- protocol/test-serialization/Cargo.toml
- protocol/test-serialization/src/test_3NKaBJsN1SehD6iJwRwJSFmVzJg5DXSUQVgnMxtH4eer4aF5BrDK.rs
- More test coverage on block fields based on gcloud json representation of block
Closes 
> M1 block serde: more field test coverage

- .github/workflows/build-and-test.yml
- base/src/lib.rs
- consensus/src/lib.rs
- crypto/src/lib.rs
- protocol/bin-prot/src/lib.rs
- protocol/wire-type-derive/src/lib.rs
- protocol/wire-type/src/lib.rs
- Add lint rule to deny doc warnings
Closes 
> Deny doc warnings

- crypto/src/hash/prefixes.rs
> const fn small refactoring

- .github/workflows/build-and-test.yml
- Fix wasm ci build break
Closes 
> Fix wasm ci

- .github/CODEOWNERS
> Add polarbeargo to codeowners

- Cargo.lock
- crypto/Cargo.toml
- crypto/src/hash/traits.rs
- update crate blake2 from ^0.9 to ^0.10
Closes 
> Update out-of-date deps

- Cargo.lock
- base/Cargo.toml
- deny.toml
- Update crate versions of o1-labs/proof-systems
- Reject unlicensed in deny.toml
Closes 
> update deny.toml to reject unlicensed

- base/src/blockchain_state.rs
- base/src/epoch_data.rs
- base/src/external_transition.rs
- 
Add comments in the BlockchainState, EpochLedger, ExternalTransition and EpochData.
Closes #105
> Address m1 review

- Cargo.lock
- apps/profilers/Cargo.toml
- apps/profilers/src/bin/block-serde-profiler.rs
- Upgrade clap from ^2 to ^3
Closes 
> Upgrade out-of-date crates

- consensus/src/common.rs
Add comments in common.rs test [discussion](https://github.com/ChainSafe/mina-rs/pull/94#discussion_r764142629)
- 
Closes 
> docs: Add comments in common.rs test

- protocol/wire-type/src/lib.rs
- Resolve https://github.com/ChainSafe/mina-rs/pull/94#discussion_r765017656
Closes 
> Test coverage for wiretypes with public fields

- .github/cargo-config
- .github/workflows/build-and-test.yml
- Use ldd on CI for faster linkage
Closes 
> Use ldd on CI for faster linkage

- .github/workflows/build-and-test.yml
- Cargo.toml
- apps/Cargo.lock
- apps/Cargo.toml
- base/src/numbers.rs
- Pin rust nightly to nightly-2022-01-14 to fix broken code coverage
Closes 
> Fix code coverage

- consensus/src/checkpoint.rs
- consensus/src/common.rs
- consensus/src/error.rs
- consensus/tests/checkpoint.rs
> minor refactors around consensus and use actual is_short_range API

- .github/workflows/build-and-test.yml
- unpin rust nightly version since llvm codecov bug has been fixed in nightly-2022-01-26
Closes 
> Unpin rust nightly version on CI (upstream llvm codecov bug fixed)

- apps/Cargo.lock
- apps/profilers/Cargo.toml
- apps/profilers/src/bin/block-serde-profiler.rs
- base/src/numbers.rs
- network/Cargo.toml
- Upgrade libp2p deps version to latest
Closes 
> Upgrade libp2p deps

- .github/CODEOWNERS
> Add shashank in codeowners

- .github/workflows/build-and-test.yml
- Run `apt update` before `apt install`
Closes 
> fix CI breakage

- consensus/tests/common.rs
- Added select longer chain test cases
- Added select secure chain test cases
Closes #165
> Additional test cases for select longer chain and select secure chain

- .github/workflows/build-and-test.yml
- .github/workflows/cancel-stale.yml
- Pin nightly to nightly-2022-03-22 as a temporary fix
- Cancel stale workflow runs automatically
Maybe we can consider pinning nightly version and update it monthly to avoid future breakage
Closes 
> Fix build break on nightly rust

- apps/wasm/mvp/static/manifest-v2.json
- apps/wasm/mvp/static/manifest.json
- apps/wasm/mvp/static/rules_cors.json
- Set cors policy for chrome extension manifest v3
- Set cors policy for chrome extension manifest v2
Closes 
> MVP - Set cors policy for chrome extensions

- base/src/consensus_state.rs
- consensus/Cargo.toml
- consensus/src/common.rs
- consensus/src/error.rs
- consensus/tests/common.rs
- Added comments for test cases 
- Used mainnet block data for some test cases
- Added following adversary test cases:
1.Adding extra sub-windows
2.Adding impossibly high sub-window densities
3.Having too small number of sub-windows
- Added error handling in relative_min_window_density
Closes #165
> Added adversary and few more test cases for select secure chain method

- .github/workflows/build-and-test.yml
- apps/Cargo.lock
- apps/wasm/Cargo.lock
- base/Cargo.toml
- base/src/account/mod.rs
- base/src/protocol_state.rs
- merkle/Cargo.toml
- merkle/src/hasher_poseidon.rs
- merkle/src/lib.rs
- merkle/src/merger_poseidon.rs
- merkle/tests/tree_poseidon.rs
- This PR removes pooling of mina hasher by making perf improvement to upstream
- Pending below PRs
https://github.com/o1-labs/proof-systems/pull/675
https://github.com/o1-labs/proof-systems/pull/677
Closes 
> M4 - Remove pooling of mina poseidon hasher

- apps/wasm/mvp/src/js_exports.rs
- base/src/staged_ledger_diff.rs
- consensus/tests/common.rs
- protocol/serialization-types/src/staged_ledger_diff.rs
- protocol/serialization-types/tests/test-serialization.rs
- protocol/test-fixtures/src/lib.rs
- protocol/test-serialization/src/test_3NKaBJsN1SehD6iJwRwJSFmVzJg5DXSUQVgnMxtH4eer4aF5BrDK.rs
> Cleanup and fixes 

- apps/Cargo.lock
- apps/wasm/Cargo.lock
- proof-systems-shim/Cargo.toml
- Update proof-systems rev
Closes 
> chore: Update proof-systems to include perf improvement of hasher creation

- consensus/src/common.rs
- consensus/tests/common.rs
- Fixes blockchainLength API as per spec
Closes 
> fix: correct consensus chain length API

- apps/Cargo.lock
- apps/wasm/Cargo.lock
- base/tests/blockchain_state.rs
- proof-systems-shim/Cargo.toml
- Update genesis block data in tests to align with latest `mina` `develop` branch
Closes 
> fix: update berkeley net genesis protocol state

- apps/wasm/Cargo.lock
- apps/wasm/mvp/Cargo.toml
- apps/wasm/mvp/src/lib.rs
- apps/wasm/mvp/src/payment.rs
- apps/wasm/mvp/src/utils.rs
- apps/wasm/mvp/web/components/NavBar.vue
- apps/wasm/mvp/web/pages/sendPayment.vue
- apps/wasm/mvp/web/sendPayment.html
- apps/wasm/mvp/web/sendPayment.ts
Enabled sending payment to berkley qanet using graphql api:
Closes #248 
> Send a payment/transaction to Berkley QAnet

- .github/workflows/build-and-test.yml
- apps/Cargo.lock
- apps/wasm/Cargo.lock
- consensus/Cargo.toml
- consensus/src/genesis/genesis_impl.rs
- consensus/src/genesis/mod.rs
- consensus/tests/berkeley.rs
- proof-systems-shim/Cargo.toml
> feat: impl GenesisProtocolState for qanet

- apps/Cargo.lock
- apps/wasm/Cargo.lock
- base/Cargo.toml
- base/src/blockchain_state.rs
- base/src/blockchain_state_registers.rs
- base/src/consensus_state.rs
- base/src/epoch_data.rs
- base/src/from_graphql_json.rs
- base/src/lib.rs
- base/src/protocol_state.rs
- base/src/user_commands/memo.rs
- consensus/src/genesis/genesis_impl.rs
- consensus/tests/common.rs
- crypto/src/hash/types.rs
- proof-systems-shim/Cargo.toml
- protocol/serialization-types/src/consensus_state.rs
- protocol/serialization-types/src/lib.rs
- Construct ProtocolState from graphql json
Closes 
> feat: Construct ProtocolState from graphql json

- apps/Cargo.lock
- apps/wasm/Cargo.lock
- apps/wasm/mvp/src/frontier.rs
- network/Cargo.toml
- network/src/processor/js/graphql_api_berkeley.rs
- network/src/processor/js/mod.rs
- network/src/processor/naive_transition_frontier.rs
- network/src/processor/processor_impl.rs
- proof-systems-shim/Cargo.toml
- NaiveTransitionFrontier implementation with finalized public APIs to unblock wasm API work  @sudo-shashank 
- TODOs will be fixed in another PR
- E2E tests will come in another PR
Closes 
> feat: Naive transition frontier berkeley

- apps/Cargo.lock
- apps/wasm/Cargo.lock
- base/Cargo.toml
- base/src/account/mod.rs
- base/src/account/permissions.rs
- base/src/account/timing.rs
- base/src/account/token_symbol.rs
- base/src/blockchain_state.rs
- base/src/protocol_state.rs
- consensus/tests/berkeley.rs
- crypto/src/hash/types.rs
- merkle/src/path.rs
- network/Cargo.toml
- network/js/graphql_berkeley_utils.js
- network/js/graphql_berkeley_utils.spec.js
- network/package.json
- network/src/processor/js/graphql_api_berkeley.rs
- network/src/processor/js/graphql_api_v1.rs
- network/src/processor/naive_transition_frontier.rs
- network/src/processor/processor_impl.rs
- network/yarn.lock
- proof-systems-shim/src/fp.rs
> feat: Complete qanet networking impl and tests
